### ISSUE TITLE
Chekpoint is too old. Wait for blockchain to download, or notify developers of the issue

### ISSUE THREAD

**Issue by MarcoAms** [GAWMiners/paycoin#27]
*WARNING:* Chekpoint is too old. Wait for blockchain to download, or notify developers of the issue

Since a reboot this warning is showing what tis means and how to fix this?

**Comment by Nerulls** [comment]
did you just install? if so wait a while and after the blockchain downloads it should stop saying that (well did for me)

**Comment by ligerzero459** [comment]
This seems to be a new issue. I've had a copy of the wallet installed for a while and it just began saying this about 2 days ago as well. It's still pulling blocks just fine, however.

**Comment by Netzarim** [comment]
This is still current in version 1.2.26.. I've installed from source on linux, and QT on windows.  The error comes up on both.  Both wallets are fully sync'd to the block chain.

**Comment by ahmedbodi** [comment]
It must be that the paycoin devs arent running a checkpoint server or the devs/wallet has invalid checkpoint server keys set

**Comment by Singman33** [comment]
From current github version, under Linux, no QT (command line only), wallet is few weeks old, daemon running since last update (2 weeks ?)  :
$ paycoind getinfo
{
    "version" : "v0.1.2.26-ge3c013c",
    "protocolversion" : 70001,
    "walletversion" : 60000,
    "balance" : 0.02400000,
    "newmint" : 0.00000000,
    "stake" : 0.00000000,
    "blocks" : 36253,
    "moneysupply" : 12394989.00877200,
    "connections" : 10,
    "proxy" : "",
    "ip" : "--.--.--.--",
    "difficulty" : 20097.90293824,
    "testnet" : false,
    "keypoololdest" : 1418721547,
    "keypoolsize" : 101,
    "paytxfee" : 0.00100000,
    "errors" : "WARNING: Checkpoint is too old. Wait for block chain to download, or notify developers of the issue."
}

**Comment by flaboy07** [comment]
Same issue here!!!

**Comment by IngCr3at1on** [comment]
https://github.com/GAWMiners/paycoin/pull/33

**Comment by IngCr3at1on** [comment]
A 'fix' for this has been merged.
